from pydantic import BaseModel, Field


class CensusSchema(BaseModel):
    Census_Country: str = Field(None, description="Census country")
    Entity_Type: int = Field(None, description="Type of the entity")
    Entity_Class: int = Field(None, description="Class of entity")
    Entity_Mode: int = Field(None, description="Mode of entity")
    Entity_Visible: str = Field(None, description="Determines if is visible Y if it is N if is not")
    Entity_Status: str = Field(None, description="Status of entity")
    Entity_Name: str = Field(None, description="Social name of the entity")
    Entity_Address_Short: str = Field(None, description="Address of the entity")
    Entity_Address_City: str = Field(None, description="City")
    Entity_Location_State: str = Field(None, description="State")
    Entity_Phone: int = Field(None, description="Phone")
    Entity_Location_Lat: str = Field(None, description="lat")
    Entity_Location_Lon: str = Field(None, description="lng")
    Entity_Stat_Nr1: int = Field(None, description="Nr1")
    Entity_Stat_Nr2: str = Field(None, description="Nr2")
    Entity_Stat_Activity_Code: int = Field(None, description="Activity Code")
    Entity_Size_Emp: str = Field(None, description="Business size")
    Entity_Log_Ref1_Type: str = Field(None, description="Ref 1")
    Entity_Log_Ref2_Type: str = Field(None, description="Ref 2 type")
    Entity_Log_Ref2_Name: str = Field(None, description="Ref 2 name")
    Entity_Log_Ref3_Name: str = Field(None, description="Ref 3 name")
    Entity_Log_Ref3_Type: str = Field(None, description="Ref 3 type")
    Entity_Address_StType: str = Field(None, description="Type")
    Entity_Address_StName: str = Field(None, description="St Name")
    Entity_Address_Number: int = Field(None, description="Number of address")
    Entity_Address_SectorType: str = Field(None, description="Square address")
    Entity_Address_SectorName: str = Field(None, description="Square address sector name")